const ALL_GENRES = `All genres`;
const CHANGE_FILTER_BY_GENRE = `CHANGE_FILTER_BY_GENRE`;
const GET_FILMS_BY_GENRE = `GET_FILMS_BY_GENRE`;

export {
  ALL_GENRES,
  CHANGE_FILTER_BY_GENRE,
  GET_FILMS_BY_GENRE,
};
